# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do

  api_key = ""
  app_identifier = "com.specure.nettest.desktop"

  before_each do |lane, options|
    api_key = app_store_connect_api_key(
      key_id: options[:key_id],
      issuer_id: options[:issuer_id],
      key_filepath: File.join(Dir.pwd, options[:key_id]+".p8")
    )
  end

  desc "Deploys to TestFlight"
  lane :deploy_to_testflight do |options|
    pilot(
      api_key: api_key,
      app_identifier: app_identifier,
      skip_waiting_for_build_processing: true,
      pkg: options[:package]
    )
  end
end
